name: Frontend Deployment

on:
  push:
    paths:
      - "FE/**"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          cd FE
          npm install
          npm run build

      - name: Upload to Naver Cloud Platform Object Storage
        env:
          NCP_ACCESS_KEY: ${{ secrets.NCP_ACCESS_KEY }}
          NCP_SECRET_KEY: ${{ secrets.NCP_SECRET_KEY }}
        run: |
          # Replace with NCP CLI commands to upload your build output (e.g., to `dist/` folder)
          ncp-cli upload ./FE/dist s3://your-bucket-name --recursive
